/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import com.sun.jdi.connect.spi.Connection;
import java.awt.event.ItemEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sai
 */
public class Add_New_Customer extends javax.swing.JFrame {

    /**
     * Creates new form Add_New_Customer
     */
    public Add_New_Customer() {
        initComponents();
        Updt_Cmb_Category();
       
    }

     java.sql.Connection con;
    PreparedStatement pst;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Add_New_Customer = new javax.swing.JLabel();
        lb_Category = new javax.swing.JLabel();
        lb_Sub_Categoty = new javax.swing.JLabel();
        cmb_Category = new javax.swing.JComboBox<>();
        cmb_Sub_Category = new javax.swing.JComboBox<>();
        lb_Price = new javax.swing.JLabel();
        tb_Price = new javax.swing.JTextField();
        lb_Cust_ID = new javax.swing.JLabel();
        lb_Mobi_No = new javax.swing.JLabel();
        lb_Name = new javax.swing.JLabel();
        lb_Address = new javax.swing.JLabel();
        tb_Mob_No = new javax.swing.JTextField();
        tb_Address = new javax.swing.JTextField();
        tb_Cust_ID = new javax.swing.JTextField();
        tb_Name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_View = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_Add_New_Customer.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 24)); // NOI18N
        lb_Add_New_Customer.setText("Add New Customer");

        lb_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Category.setText("Category :");

        lb_Sub_Categoty.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Sub_Categoty.setText("Sub-Category :");

        cmb_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_CategoryItemStateChanged(evt);
            }
        });

        cmb_Sub_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Sub_Category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_Sub_CategoryItemStateChanged(evt);
            }
        });
        cmb_Sub_Category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_Sub_CategoryMouseClicked(evt);
            }
        });

        lb_Price.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Price.setText("Price:");

        tb_Price.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_Cust_ID.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Cust_ID.setText("Cust_ID:");

        lb_Mobi_No.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Mobi_No.setText("Mobile Number");

        lb_Name.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Name.setText("Name");

        lb_Address.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Address.setText("Address");

        tb_Mob_No.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        tb_Address.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        tb_Cust_ID.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        tb_Name.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        table_View.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Back Camera", "Front Camera", "Colour", "Price", "RAM", "Storage", "Warrenty", "Display"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_View.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(table_View);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 334, Short.MAX_VALUE)
                .addComponent(lb_Add_New_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(484, 484, 484))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Sub_Categoty, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_Mobi_No, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_Cust_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tb_Cust_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tb_Mob_No, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tb_Price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_Add_New_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Cust_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tb_Cust_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_Mobi_No, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(lb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_Sub_Categoty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tb_Mob_No, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_CategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_CategoryItemStateChanged
            
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
             
             String sql = "Select Sub_Category From tb_Sub_Category Where Category = '"+cmb_Category.getSelectedItem()+"' ";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            cmb_Sub_Category.removeAllItems();
            while(rs.next()){
                cmb_Sub_Category.addItem(rs.getString("Sub_Category"));
            }
           
            pst.close();
            rs.close();
            con.close();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
            
             
             

    }//GEN-LAST:event_cmb_CategoryItemStateChanged

    private void cmb_Sub_CategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_Sub_CategoryMouseClicked
       
    }//GEN-LAST:event_cmb_Sub_CategoryMouseClicked

    private void cmb_Sub_CategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_Sub_CategoryItemStateChanged
       Table_View();
    }//GEN-LAST:event_cmb_Sub_CategoryItemStateChanged

     public void Updt_Cmb_Category(){
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            
            String sql = "Select *from tb_Category";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            while(rs.next()){
                cmb_Category.addItem(rs.getString("Category"));
            }
           
            pst.close();
            rs.close();
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add_Sub_Category.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Add_Sub_Category.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
     
     java.sql.Connection con1 ;
     PreparedStatement insert;
    private void Table_View(){
         int c;
         
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            insert = con1.prepareStatement("select * From tb_Product_Details where Category = '"+cmb_Category.getSelectedItem()+"' And Sub_Category = '"+cmb_Sub_Category.getSelectedItem()+"'  ");
            
            ResultSet rs = insert.executeQuery();
             ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
             c = rsmd.getColumnCount();
             DefaultTableModel Dtm = (DefaultTableModel) table_View.getModel();
            
           Dtm.setRowCount(0);
           
           while(rs.next()){
               Vector v2 = new Vector();
               for(int i = 1 ; i <= c; i++)
               {
                    v2.add(rs.getString("Prod_ID"));
                    v2.add(rs.getString("Back_Camera"));
                    v2.add(rs.getString("Front_Camera"));
                    v2.add(rs.getString("Colour"));
                    v2.add(rs.getString("Price"));
                    v2.add(rs.getString("RAM"));
                    v2.add(rs.getString("Storage"));
                    v2.add(rs.getString("Warrenty"));
                    v2.add(rs.getString("Display"));
               }
               Dtm.addRow(v2);
           }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_New_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_New_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_New_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_New_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_New_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_Category;
    private javax.swing.JComboBox<String> cmb_Sub_Category;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Add_New_Customer;
    private javax.swing.JLabel lb_Address;
    private javax.swing.JLabel lb_Category;
    private javax.swing.JLabel lb_Cust_ID;
    private javax.swing.JLabel lb_Mobi_No;
    private javax.swing.JLabel lb_Name;
    private javax.swing.JLabel lb_Price;
    private javax.swing.JLabel lb_Sub_Categoty;
    private javax.swing.JTable table_View;
    private javax.swing.JTextField tb_Address;
    private javax.swing.JTextField tb_Cust_ID;
    private javax.swing.JTextField tb_Mob_No;
    private javax.swing.JTextField tb_Name;
    private javax.swing.JTextField tb_Price;
    // End of variables declaration//GEN-END:variables
}
