/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sai
 */
public class frm_View_All_Customer extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_View_All_Customer
     */
    public frm_View_All_Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Customer_Details = new javax.swing.JTable();
        lb_Customer_ID = new javax.swing.JLabel();
        tb_Customer_ID = new javax.swing.JTextField();
        btn_Search = new javax.swing.JButton();
        btn_View_All_Customer = new javax.swing.JButton();
        lb_Bill1 = new javax.swing.JLabel();
        tb_SGST = new javax.swing.JTextField();
        lb_Bill2 = new javax.swing.JLabel();
        tb_CGST = new javax.swing.JTextField();
        lb_Bill3 = new javax.swing.JLabel();
        tb_Total_Bill = new javax.swing.JTextField();

        Table_Customer_Details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cust_ID", "Name", "Mobile_Number", "Address", "Prod_ID", "Category", "Sub_Category", "Price"
            }
        ));
        jScrollPane1.setViewportView(Table_Customer_Details);

        lb_Customer_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_Customer_ID.setText("Customer ID ");

        tb_Customer_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Search.setText("Search");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        btn_View_All_Customer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_View_All_Customer.setText("View All Customer");
        btn_View_All_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_View_All_CustomerActionPerformed(evt);
            }
        });

        lb_Bill1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Bill1.setText("SGST");

        tb_SGST.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lb_Bill2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Bill2.setText("CGST");

        tb_CGST.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lb_Bill3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Bill3.setText("Total Bill");

        tb_Total_Bill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tb_SGST, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Bill1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_CGST, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Bill2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_Total_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Bill3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_Customer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tb_Customer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_View_All_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Customer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_Customer_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_View_All_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_Bill1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_SGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_Bill2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_CGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_Bill3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_Total_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     java.sql.Connection con;
        PreparedStatement pst;
        
    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
                                                
            try {
                int c = 0;
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
                pst = con.prepareStatement("select * From add_Customer Where Cust_ID = '"+tb_Customer_ID.getText()+"' ");
                
                ResultSet rs = pst.executeQuery();
                ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
                c = rsmd.getColumnCount();
                DefaultTableModel Dtm = (DefaultTableModel) Table_Customer_Details.getModel();
                
                Dtm.setRowCount(0);
                
                while(rs.next()){
                    Vector v2 = new Vector();
                    for(int i = 1 ; i <= c; i++)
                    {
                        v2.add(rs.getString("Cust_ID"));
                        v2.add(rs.getString("Name"));
                        v2.add(rs.getString("Mob_No"));
                        v2.add(rs.getString("Address"));
                        v2.add(rs.getString("Prod_ID"));
                        v2.add(rs.getString("Category"));
                        v2.add(rs.getString("Sub_Category"));
                        v2.add(rs.getString("Price"));
                        
                        
                    }
                    Dtm.addRow(v2);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frm_View_All_Customer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(frm_View_All_Customer.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //...
            
            try {  
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            String sql = "Select * From add_Customer_Info where Cust_ID = '"+tb_Customer_ID.getText()+"' " ;
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();

            if(rs.next()){
                tb_SGST.setText(rs.getString("SGST"));
                tb_CGST.setText(rs.getString("CGST"));
                tb_Total_Bill.setText(rs.getString("Total"));
            }

            
        } catch (SQLException ex) {
            Logger.getLogger(frm_View_All_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_View_All_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
            
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void btn_View_All_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_View_All_CustomerActionPerformed
         try {
            int c = 0;
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            pst = con.prepareStatement("select * From add_Customer ");
            
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
            c = rsmd.getColumnCount();
            DefaultTableModel Dtm = (DefaultTableModel) Table_Customer_Details.getModel();
            
            Dtm.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                for(int i = 1 ; i <= c; i++)
                {
                     v2.add(rs.getString("Cust_ID"));
                     v2.add(rs.getString("Name"));
                     v2.add(rs.getString("Mob_No"));
                     v2.add(rs.getString("Address"));
                     v2.add(rs.getString("Prod_ID"));
                     v2.add(rs.getString("Category"));
                     v2.add(rs.getString("Sub_Category"));
                     v2.add(rs.getString("Price"));
                   
                    
                }
                Dtm.addRow(v2);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_View_All_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_View_All_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_View_All_CustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Customer_Details;
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_View_All_Customer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Bill1;
    private javax.swing.JLabel lb_Bill2;
    private javax.swing.JLabel lb_Bill3;
    private javax.swing.JLabel lb_Customer_ID;
    private javax.swing.JTextField tb_CGST;
    private javax.swing.JTextField tb_Customer_ID;
    private javax.swing.JTextField tb_SGST;
    private javax.swing.JTextField tb_Total_Bill;
    // End of variables declaration//GEN-END:variables
}
