/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;
import com.mysql.cj.xdevapi.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.lang.String;
import javax.swing.JOptionPane;
/**
 *
 * @author sai
 */
public class frm_Add_New_Product extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_Add_New_Product
     */
    public frm_Add_New_Product() {
        initComponents();
         Updt_Cmb_Category();
        Auto_ID();
        cmb_Category.setSelectedIndex(-1);
        cmb_Sub_Category.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Product_ID = new javax.swing.JLabel();
        tb_Product_ID = new javax.swing.JTextField();
        lb_Display = new javax.swing.JLabel();
        cmb_Display = new javax.swing.JComboBox<>();
        lb_Category = new javax.swing.JLabel();
        cmb_Category = new javax.swing.JComboBox<>();
        lb_Front_Camera = new javax.swing.JLabel();
        cmb_Front_Camera = new javax.swing.JComboBox<>();
        lb_Sub_Categoty = new javax.swing.JLabel();
        cmb_Sub_Category = new javax.swing.JComboBox<>();
        lb_Back_Camera = new javax.swing.JLabel();
        cmb_Back_Camera = new javax.swing.JComboBox<>();
        lb_Purches_Price = new javax.swing.JLabel();
        tb_Purches_Price = new javax.swing.JTextField();
        lb_Warrenty = new javax.swing.JLabel();
        cmb_Warrenty = new javax.swing.JComboBox<>();
        lb_Saling_Price = new javax.swing.JLabel();
        tb_Saling_Price = new javax.swing.JTextField();
        lb_Internal_Storage = new javax.swing.JLabel();
        cmb_Storage = new javax.swing.JComboBox<>();
        lb_Quantity = new javax.swing.JLabel();
        tb_Quantity = new javax.swing.JTextField();
        lb_Colour = new javax.swing.JLabel();
        cmb_Colour = new javax.swing.JComboBox<>();
        btn_Add = new javax.swing.JButton();
        lb_Add_Category = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add New Product");
        setPreferredSize(new java.awt.Dimension(1300, 781));

        lb_Product_ID.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Product_ID.setText("Product ID:");

        tb_Product_ID.setEditable(false);
        tb_Product_ID.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tb_Product_ID.setEnabled(false);

        lb_Display.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Display.setText("Display:");

        cmb_Display.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Display.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4.65 inches", "5.40 inches", "6.53 inches" }));
        cmb_Display.setSelectedIndex(-1);

        lb_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Category.setText("Category :");

        cmb_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_CategoryItemStateChanged(evt);
            }
        });

        lb_Front_Camera.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Front_Camera.setText("Front Camera");

        cmb_Front_Camera.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Front_Camera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13 MP", "32 PM", "8MP" }));
        cmb_Front_Camera.setSelectedIndex(-1);

        lb_Sub_Categoty.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Sub_Categoty.setText("Sub-Category :");

        cmb_Sub_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_Back_Camera.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Back_Camera.setText("Back Camera");

        cmb_Back_Camera.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Back_Camera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "32MP", "48MP" }));
        cmb_Back_Camera.setSelectedIndex(-1);

        lb_Purches_Price.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Purches_Price.setText("Purches Price:");

        tb_Purches_Price.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_Warrenty.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Warrenty.setText("Warranty");

        cmb_Warrenty.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Warrenty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Year", "1.5 Year" }));
        cmb_Warrenty.setSelectedIndex(-1);

        lb_Saling_Price.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Saling_Price.setText("Saling Price");

        tb_Saling_Price.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_Internal_Storage.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Internal_Storage.setText("Internal Storage");

        cmb_Storage.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Storage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 / 64 ", "4 / 128 ", "6 / 128" }));
        cmb_Storage.setSelectedIndex(-1);

        lb_Quantity.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Quantity.setText("Quantity:");

        tb_Quantity.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_Colour.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Colour.setText("Colour");

        cmb_Colour.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Colour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "white", "Black", " " }));
        cmb_Colour.setSelectedIndex(-1);

        btn_Add.setText("ADD");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        lb_Add_Category.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 24)); // NOI18N
        lb_Add_Category.setText("Add New Product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(lb_Add_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(644, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_Product_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_Sub_Categoty, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_Purches_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(69, 69, 69)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tb_Product_ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cmb_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tb_Purches_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tb_Saling_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tb_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(1, 1, 1))))
                                .addComponent(lb_Saling_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lb_Internal_Storage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_Display, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_Colour, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_Back_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_Front_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lb_Warrenty, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_Warrenty, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_Display, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_Storage, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cmb_Front_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_Back_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_Colour, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(444, 444, 444)
                            .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(11, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Add_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(701, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb_Product_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(lb_Sub_Categoty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(lb_Purches_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tb_Product_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(93, 93, 93)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmb_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_Back_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_Back_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tb_Purches_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_Warrenty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_Warrenty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_Internal_Storage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_Storage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_Saling_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tb_Saling_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_Front_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_Front_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Colour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Colour, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lb_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(96, 96, 96)
                    .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     Connection con;
    PreparedStatement pst;
    private void cmb_CategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_CategoryItemStateChanged

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            String sql = "Select Sub_Category From tb_Sub_Category Where Category = '"+cmb_Category.getSelectedItem()+"' ";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            cmb_Sub_Category.removeAllItems();
            while(rs.next()){
                cmb_Sub_Category.addItem(rs.getString("Sub_Category"));
            }

            pst.close();
            rs.close();
            con.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Product.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Product.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmb_CategoryItemStateChanged

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            pst = con.prepareStatement("INSERT INTO tb_Product_Details(Prod_ID,Category,Sub_Category,Purches_Price,Saling_Price,Quantity,Warrenty,Display,Storage,Front_Camera,Back_Camera,Colour) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, tb_Product_ID.getText());
            pst.setString(2, cmb_Category.getSelectedItem().toString());
            pst.setString(3, cmb_Sub_Category.getSelectedItem().toString());
            pst.setString(4, tb_Purches_Price.getText());
            pst.setString(5, tb_Saling_Price.getText());
            pst.setString(6, tb_Quantity.getText());
            pst.setString(7, cmb_Warrenty.getSelectedItem().toString());
            pst.setString(8, cmb_Display.getSelectedItem().toString());
            pst.setString(9, cmb_Storage.getSelectedItem().toString());
            pst.setString(10, cmb_Front_Camera.getSelectedItem().toString());
            pst.setString(11, cmb_Back_Camera.getSelectedItem().toString());
            pst.setString(12, cmb_Colour.getSelectedItem().toString());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Product Added SuccessFully..");

            tb_Purches_Price.setText("");
            tb_Saling_Price.setText("");
            tb_Quantity.setText("");
            cmb_Warrenty.setSelectedIndex(-1);
            cmb_Display.setSelectedIndex(-1);
            cmb_Storage.setSelectedIndex(-1);
            cmb_Front_Camera.setSelectedIndex(-1);
            cmb_Back_Camera.setSelectedIndex(-1);
            cmb_Colour.setSelectedIndex(-1);
            cmb_Category.setSelectedIndex(-1);
            cmb_Sub_Category.setSelectedIndex(-1);
            Auto_ID();

            pst.close();

            con.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Category.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Category.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_AddActionPerformed

     public void Auto_ID() {
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            
             String sql = "select max(Prod_ID) From tb_Product_Details";
             pst = con.prepareStatement(sql);
            
             ResultSet rs = pst.executeQuery();
             if(rs.next()){
                int Prod_ID = rs.getInt(1);
                 Prod_ID++;
                 tb_Product_ID.setText(Integer.toString(Prod_ID));
             }
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Product.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Product.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
     
      public void Updt_Cmb_Category(){
     
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
        
            String sql = "Select *from tb_Category";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            
            while(rs.next()){
                cmb_Category.addItem(rs.getString("Category"));
            }
           
            pst.close();
            rs.close();
            con.close();
                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Product.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Product.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JComboBox<String> cmb_Back_Camera;
    private javax.swing.JComboBox<String> cmb_Category;
    private javax.swing.JComboBox<String> cmb_Colour;
    private javax.swing.JComboBox<String> cmb_Display;
    private javax.swing.JComboBox<String> cmb_Front_Camera;
    private javax.swing.JComboBox<String> cmb_Storage;
    private javax.swing.JComboBox<String> cmb_Sub_Category;
    private javax.swing.JComboBox<String> cmb_Warrenty;
    private javax.swing.JLabel lb_Add_Category;
    private javax.swing.JLabel lb_Back_Camera;
    private javax.swing.JLabel lb_Category;
    private javax.swing.JLabel lb_Colour;
    private javax.swing.JLabel lb_Display;
    private javax.swing.JLabel lb_Front_Camera;
    private javax.swing.JLabel lb_Internal_Storage;
    private javax.swing.JLabel lb_Product_ID;
    private javax.swing.JLabel lb_Purches_Price;
    private javax.swing.JLabel lb_Quantity;
    private javax.swing.JLabel lb_Saling_Price;
    private javax.swing.JLabel lb_Sub_Categoty;
    private javax.swing.JLabel lb_Warrenty;
    private javax.swing.JTextField tb_Product_ID;
    private javax.swing.JTextField tb_Purches_Price;
    private javax.swing.JTextField tb_Quantity;
    private javax.swing.JTextField tb_Saling_Price;
    // End of variables declaration//GEN-END:variables
}
