/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;

import com.sun.jdi.connect.spi.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author sai
 */
public class frm_Add_Stock extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_Add_Stock
     */
    public frm_Add_Stock() {
        initComponents();
         Updt_Cmb_Category();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Category = new javax.swing.JLabel();
        cmb_Category = new javax.swing.JComboBox<>();
        lb_Sub_Categoty = new javax.swing.JLabel();
        cmb_Sub_Category = new javax.swing.JComboBox<>();
        lb_Internal_Storage = new javax.swing.JLabel();
        cmb_Storage = new javax.swing.JComboBox<>();
        lb_Colour = new javax.swing.JLabel();
        cmb_Colour = new javax.swing.JComboBox<>();
        lb_Remaining_Stock = new javax.swing.JLabel();
        tb_Remaining_Stock = new javax.swing.JTextField();
        lb_Add_Stock = new javax.swing.JLabel();
        tb_Add_Stock = new javax.swing.JTextField();
        btn_Add = new javax.swing.JButton();
        lb__Add_Stock = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        lb_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Category.setText("Category :");

        cmb_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_CategoryItemStateChanged(evt);
            }
        });

        lb_Sub_Categoty.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Sub_Categoty.setText("Sub-Category :");

        cmb_Sub_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Sub_Category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_Sub_CategoryItemStateChanged(evt);
            }
        });

        lb_Internal_Storage.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Internal_Storage.setText("Internal Storage");

        cmb_Storage.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_Colour.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Colour.setText("Colour");

        cmb_Colour.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Colour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "white", "Black", " " }));
        cmb_Colour.setSelectedIndex(-1);

        lb_Remaining_Stock.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Remaining_Stock.setText("Remaining Stock");

        tb_Remaining_Stock.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tb_Remaining_Stock.setEnabled(false);

        lb_Add_Stock.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Add_Stock.setText("Add Stock");

        tb_Add_Stock.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        btn_Add.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        lb__Add_Stock.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        lb__Add_Stock.setText("ADD STOCK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(lb__Add_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(171, 171, 171)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_Internal_Storage, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_Remaining_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tb_Remaining_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_Colour, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_Colour, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_Sub_Categoty, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmb_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_Storage, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_Add_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tb_Add_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(172, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb__Add_Stock)
                .addContainerGap(536, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(lb_Sub_Categoty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(cmb_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cmb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_Internal_Storage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_Storage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_Colour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_Colour, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tb_Remaining_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_Remaining_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tb_Add_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_Add_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(43, 43, 43)
                    .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(73, 73, 73)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     java.sql.Connection con;
    PreparedStatement pst;
    private void cmb_CategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_CategoryItemStateChanged

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            String sql = "Select Sub_Category From tb_Sub_Category Where Category = '"+cmb_Category.getSelectedItem()+"' ";
             pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            cmb_Sub_Category.removeAllItems();
            while(rs.next()){
                cmb_Sub_Category.addItem(rs.getString("Sub_Category"));
            }

            pst.close();
            rs.close();
            con.close();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frm_Add_Stock.class.getName()).log(Level.SEVERE, null, ex);
        }

        //.........

    }//GEN-LAST:event_cmb_CategoryItemStateChanged

    private void cmb_Sub_CategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_Sub_CategoryItemStateChanged
        //for Storage
        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            String sql = "Select * From tb_product_details where Category = '"+cmb_Category.getSelectedItem()+"' And Sub_Category = '"+cmb_Sub_Category.getSelectedItem()+"' " ;
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            cmb_Storage.removeAllItems();
            while(rs.next()){
                cmb_Storage.addItem(rs.getString("Storage"));
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frm_Add_Stock.class.getName()).log(Level.SEVERE, null, ex);
        }

        //... for colour

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            String sql = "Select * From tb_product_details where Category = '"+cmb_Category.getSelectedItem()+"' And Sub_Category = '"+cmb_Sub_Category.getSelectedItem()+"' " ;
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            cmb_Colour.removeAllItems();
            while(rs.next()){
                cmb_Colour.addItem(rs.getString("Colour"));
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frm_Add_Stock.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Remaining Stock

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            String sql = "Select * From tb_product_details where Category = '"+cmb_Category.getSelectedItem()+"' And Sub_Category = '"+cmb_Sub_Category.getSelectedItem()+"' " ;
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();

            if(rs.next()){
                tb_Remaining_Stock.setText(rs.getString("Quantity"));
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frm_Add_Stock.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmb_Sub_CategoryItemStateChanged

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        int Prev_Stock =  Integer.parseInt(tb_Remaining_Stock.getText());
        int Add_Stock = Integer.parseInt(tb_Add_Stock.getText());

        int Total = Prev_Stock + Add_Stock;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            pst = con.prepareStatement("Update  tb_Product_Details set Quantity = ? where Category = '"+cmb_Category.getSelectedItem()+"' And Sub_Category = '"+cmb_Sub_Category.getSelectedItem()+"'");
            pst.setString(1,String.valueOf(Total));

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, " Stock Added SuccessFully.." +"\n" + " Now Stock Count Is " + Total);

            tb_Remaining_Stock.setText(null);
            tb_Add_Stock.setText(null);
            cmb_Category.setSelectedIndex(-1);
            cmb_Sub_Category.setSelectedIndex(-1);
            cmb_Storage.setSelectedIndex(-1);
            cmb_Colour.setSelectedIndex(-1);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_Stock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_Stock.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_AddActionPerformed

     public void Updt_Cmb_Category(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
           
             String sql = "Select *from tb_Category";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            while(rs.next()){
                cmb_Category.addItem(rs.getString("Category"));
            }
           
            pst.close();
            rs.close();
            con.close();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_Stock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JComboBox<String> cmb_Category;
    private javax.swing.JComboBox<String> cmb_Colour;
    private javax.swing.JComboBox<String> cmb_Storage;
    private javax.swing.JComboBox<String> cmb_Sub_Category;
    private javax.swing.JLabel lb_Add_Stock;
    private javax.swing.JLabel lb_Category;
    private javax.swing.JLabel lb_Colour;
    private javax.swing.JLabel lb_Internal_Storage;
    private javax.swing.JLabel lb_Remaining_Stock;
    private javax.swing.JLabel lb_Sub_Categoty;
    private javax.swing.JLabel lb__Add_Stock;
    private javax.swing.JTextField tb_Add_Stock;
    private javax.swing.JTextField tb_Remaining_Stock;
    // End of variables declaration//GEN-END:variables
}
