/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sai
 */
public class frm_Update_Distrubutor_Info extends javax.swing.JInternalFrame {

   
    public frm_Update_Distrubutor_Info() {
        initComponents();
         tb_ID.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Distrubutor_ID = new javax.swing.JLabel();
        tb_ID = new javax.swing.JTextField();
        lb_Mob_No = new javax.swing.JLabel();
        tb_Mobile_No = new javax.swing.JTextField();
        lb_Name = new javax.swing.JLabel();
        tb_Name = new javax.swing.JTextField();
        lb_PAN_No = new javax.swing.JLabel();
        tb_PAN_No = new javax.swing.JTextField();
        lb_Address = new javax.swing.JLabel();
        tb_Address = new javax.swing.JTextField();
        lb_Adhar_Card_No = new javax.swing.JLabel();
        tb_Adhar_Card_No = new javax.swing.JTextField();
        lb_E_mail = new javax.swing.JLabel();
        tb_E_Mail = new javax.swing.JTextField();
        btn_Search = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();

        lb_Distrubutor_ID.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Distrubutor_ID.setText("Distrubutor ID");

        tb_ID.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_Mob_No.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Mob_No.setText("Mobile No");

        tb_Mobile_No.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_Name.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Name.setText("Name");

        tb_Name.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_PAN_No.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_PAN_No.setText("PAN No");

        tb_PAN_No.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_Address.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Address.setText("Address");

        tb_Address.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_Adhar_Card_No.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Adhar_Card_No.setText("Adhar Card No");

        tb_Adhar_Card_No.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_E_mail.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_E_mail.setText("E-mail");

        tb_E_Mail.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        btn_Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Search.setText("Search");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(tb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(tb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))
                                    .addComponent(lb_E_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addComponent(tb_E_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_PAN_No, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(tb_PAN_No, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_Mob_No, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(tb_Mobile_No, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_Adhar_Card_No, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(tb_Adhar_Card_No))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_Distrubutor_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(tb_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Distrubutor_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_E_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_E_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_Mob_No, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_Mobile_No, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addComponent(tb_Adhar_Card_No, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_PAN_No, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb_PAN_No, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(lb_Adhar_Card_No, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97)
                .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     java.sql.Connection con;
        PreparedStatement pst;
    
    /**/
    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        
        try {
               
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            
            pst = con.prepareStatement("select * From distrubutor_info Where Distrubutor_ID = ? " );
             int id = Integer.parseInt(tb_ID.getText());
             pst.setInt(1, id);
           
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
               
                tb_Name.setText(rs.getString("Name"));
                tb_Address.setText(rs.getString("Address"));
                tb_Mobile_No.setText(rs.getString("Mob_No"));
                tb_PAN_No.setText(rs.getString("PAN_No"));
                tb_Adhar_Card_No.setText(rs.getString("AdharCard_No"));
                tb_E_Mail.setText(rs.getString("E_Mail"));
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Sorry..Not Available");
                   
            }
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, "/..");
            Logger.getLogger(frm_Update_Distrubutor_Info.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Update_Distrubutor_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            
            pst = con.prepareStatement("Update  distrubutor_info set Name = ? , Address = ? ,Mob_No = ? , PAN_No = ? ,AdharCard_No = ?, E_Mail = ? where Distrubutor_ID  = '"+tb_ID.getText()+"' ");
            pst.setString(1,tb_Name.getText());
            pst.setString(2,tb_Address.getText());
            pst.setString(3,tb_Mobile_No.getText());
            pst.setString(4,tb_PAN_No.getText());
            pst.setString(5,tb_Adhar_Card_No.getText());
            pst.setString(6,tb_E_Mail.getText());
            
            pst.executeUpdate();
             JOptionPane.showMessageDialog(this, "Updated Succesfully");
                  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Update_Distrubutor_Info.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Update_Distrubutor_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_Update;
    private javax.swing.JLabel lb_Address;
    private javax.swing.JLabel lb_Adhar_Card_No;
    private javax.swing.JLabel lb_Distrubutor_ID;
    private javax.swing.JLabel lb_E_mail;
    private javax.swing.JLabel lb_Mob_No;
    private javax.swing.JLabel lb_Name;
    private javax.swing.JLabel lb_PAN_No;
    private javax.swing.JTextField tb_Address;
    private javax.swing.JTextField tb_Adhar_Card_No;
    private javax.swing.JTextField tb_E_Mail;
    private javax.swing.JTextField tb_ID;
    private javax.swing.JTextField tb_Mobile_No;
    private javax.swing.JTextField tb_Name;
    private javax.swing.JTextField tb_PAN_No;
    // End of variables declaration//GEN-END:variables
}
