/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;

/**
 *
 * @author sai
 */
public class frm_Distrubutor extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_Distrubutor
     */
    public frm_Distrubutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_Header = new javax.swing.JPanel();
        btn_Add_New_Distributor = new javax.swing.JButton();
        btn_Distrubutor_Details = new javax.swing.JButton();
        btn_Update_Details = new javax.swing.JButton();
        pnl_Body = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        btn_Add_New_Distributor.setText("Add New Distrubutor");
        btn_Add_New_Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_New_DistributorActionPerformed(evt);
            }
        });

        btn_Distrubutor_Details.setText("View  Distrubutor Details ");
        btn_Distrubutor_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Distrubutor_DetailsActionPerformed(evt);
            }
        });

        btn_Update_Details.setText("Update Details");
        btn_Update_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_DetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_HeaderLayout = new javax.swing.GroupLayout(Pnl_Header);
        Pnl_Header.setLayout(Pnl_HeaderLayout);
        Pnl_HeaderLayout.setHorizontalGroup(
            Pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Add_New_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Distrubutor_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Update_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(792, Short.MAX_VALUE))
        );
        Pnl_HeaderLayout.setVerticalGroup(
            Pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_HeaderLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(Pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Add_New_Distributor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Distrubutor_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Update_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_BodyLayout = new javax.swing.GroupLayout(pnl_Body);
        pnl_Body.setLayout(pnl_BodyLayout);
        pnl_BodyLayout.setHorizontalGroup(
            pnl_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1275, Short.MAX_VALUE)
        );
        pnl_BodyLayout.setVerticalGroup(
            pnl_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(pnl_Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Pnl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 684, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(pnl_Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Add_New_DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_New_DistributorActionPerformed
        pnl_Body.removeAll();
        pnl_Body.repaint();
        frm_Add_New_Distrubutor obj = new frm_Add_New_Distrubutor();
        pnl_Body.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_Add_New_DistributorActionPerformed

    private void btn_Distrubutor_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Distrubutor_DetailsActionPerformed
         pnl_Body.removeAll();
        pnl_Body.repaint();
        frm_View_Distrubutor_Details obj = new frm_View_Distrubutor_Details();
        pnl_Body.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_Distrubutor_DetailsActionPerformed

    private void btn_Update_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_DetailsActionPerformed
        pnl_Body.removeAll();
        pnl_Body.repaint();
        frm_Update_Distrubutor_Info obj = new frm_Update_Distrubutor_Info();
        pnl_Body.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_Update_DetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_Header;
    private javax.swing.JButton btn_Add_New_Distributor;
    private javax.swing.JButton btn_Distrubutor_Details;
    private javax.swing.JButton btn_Update_Details;
    private javax.swing.JPanel pnl_Body;
    // End of variables declaration//GEN-END:variables
}
