/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sai
 */
public class frm_View_Stocks extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_View_Stocks
     */
    public frm_View_Stocks() {
        initComponents();
          Updt_Cmb_Category();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_View = new javax.swing.JTable();
        lb__Add_Stock = new javax.swing.JLabel();
        lb_Category = new javax.swing.JLabel();
        cmb_Category = new javax.swing.JComboBox<>();
        lb_Sub_Categoty = new javax.swing.JLabel();
        cmb_Sub_Category = new javax.swing.JComboBox<>();
        btn_All_Stock = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        Table_View.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prod_ID", "Category", "Sub_Category", "Purches_Price", "Saling_Price", "Display", "Storage", "Colour", "Back_Camera", "Front_Camera", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(Table_View);

        lb__Add_Stock.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        lb__Add_Stock.setText("Stocks");

        lb_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Category.setText("Category :");

        cmb_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_CategoryItemStateChanged(evt);
            }
        });
        cmb_Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_CategoryActionPerformed(evt);
            }
        });

        lb_Sub_Categoty.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Sub_Categoty.setText("Sub-Category :");

        cmb_Sub_Category.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cmb_Sub_Category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_Sub_CategoryItemStateChanged(evt);
            }
        });
        cmb_Sub_Category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_Sub_CategoryMouseClicked(evt);
            }
        });

        btn_All_Stock.setText("All Stock");
        btn_All_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_All_StockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(lb__Add_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Sub_Categoty, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addComponent(btn_All_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb__Add_Stock)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_Sub_Categoty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_All_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    java.sql.Connection con;
        PreparedStatement pst;
        
        
        public void Updt_Cmb_Category(){
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
               con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
          
            String sql = "Select *from tb_Category";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            while(rs.next()){
                cmb_Category.addItem(rs.getString("Category"));
            }
           
          
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_View_Stocks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_View_Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
           
       
    }
    private void cmb_CategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_CategoryItemStateChanged

        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            String sql = "Select Sub_Category From tb_Sub_Category Where Category = '"+cmb_Category.getSelectedItem()+"' ";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            cmb_Sub_Category.removeAllItems();
            while(rs.next()){
                cmb_Sub_Category.addItem(rs.getString("Sub_Category"));
            }

            pst.close();
            rs.close();
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_View_Stocks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_View_Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }

       

    }//GEN-LAST:event_cmb_CategoryItemStateChanged

    
    private void cmb_CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_CategoryActionPerformed

    private void cmb_Sub_CategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_Sub_CategoryItemStateChanged
       Table_View();
    }//GEN-LAST:event_cmb_Sub_CategoryItemStateChanged

    private void cmb_Sub_CategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_Sub_CategoryMouseClicked

    }//GEN-LAST:event_cmb_Sub_CategoryMouseClicked

    private void btn_All_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_All_StockActionPerformed
         int c = 0;
         cmb_Category.setSelectedIndex(-1);
         cmb_Sub_Category.setSelectedIndex(-1);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
              con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            pst = con.prepareStatement("select * From tb_Product_Details  ");
            
            ResultSet rs = pst.executeQuery();
             ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
             c = rsmd.getColumnCount();
             DefaultTableModel Dtm = (DefaultTableModel) Table_View.getModel();
            
           Dtm.setRowCount(0);
           
            while(rs.next()){
               Vector v2 = new Vector();
               for(int i = 1 ; i <= c; i++)
               {
                    v2.add(rs.getString("Prod_ID"));
                    v2.add(rs.getString("Category"));
                    v2.add(rs.getString("Sub_Category"));
                    v2.add(rs.getString("Purches_Price"));
                    v2.add(rs.getString("Saling_Price"));
                    v2.add(rs.getString("Display"));
                    v2.add(rs.getString("Storage"));
                    v2.add(rs.getString("Colour"));
                    v2.add(rs.getString("Back_Camera"));
                    v2.add(rs.getString("Front_Camera"));
                    v2.add(rs.getString("Quantity"));
                 
               }
               Dtm.addRow(v2);
           }
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_View_Stocks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_View_Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_All_StockActionPerformed

     private void Table_View(){
     int c = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
              con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            pst = con.prepareStatement("select * From tb_Product_Details where Category = '"+cmb_Category.getSelectedItem()+"' And Sub_Category = '"+cmb_Sub_Category.getSelectedItem()+"'  ");
            
            ResultSet rs = pst.executeQuery();
             ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
             c = rsmd.getColumnCount();
             DefaultTableModel Dtm = (DefaultTableModel) Table_View.getModel();
            
           Dtm.setRowCount(0);
           
            while(rs.next()){
               Vector v2 = new Vector();
               for(int i = 1 ; i <= c; i++)
               {
                    v2.add(rs.getString("Prod_ID"));
                    v2.add(rs.getString("Category"));
                    v2.add(rs.getString("Sub_Category"));
                    v2.add(rs.getString("Purches_Price"));
                    v2.add(rs.getString("Saling_Price"));
                    v2.add(rs.getString("Display"));
                    v2.add(rs.getString("Storage"));
                    v2.add(rs.getString("Colour"));
                    v2.add(rs.getString("Back_Camera"));
                    v2.add(rs.getString("Front_Camera"));
                    v2.add(rs.getString("Quantity"));
                 
               }
               Dtm.addRow(v2);
           }
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_View_Stocks.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_View_Stocks.class.getName()).log(Level.SEVERE, null, ex);
        }
          
            
            
     }
            
            
            
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_View;
    private javax.swing.JButton btn_All_Stock;
    private javax.swing.JComboBox<String> cmb_Category;
    private javax.swing.JComboBox<String> cmb_Sub_Category;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Category;
    private javax.swing.JLabel lb_Sub_Categoty;
    private javax.swing.JLabel lb__Add_Stock;
    // End of variables declaration//GEN-END:variables
}
