/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author sai
 */
public class frm_Add_New_Customer extends javax.swing.JInternalFrame {

  
    public frm_Add_New_Customer() {
        initComponents();
        Updt_Cmb_Category();
         tb_Bill.setText(String.valueOf(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Cust_ID = new javax.swing.JLabel();
        tb_Cust_ID = new javax.swing.JTextField();
        lb_Name = new javax.swing.JLabel();
        tb_Name = new javax.swing.JTextField();
        lb_Mobi_No = new javax.swing.JLabel();
        tb_Mob_No = new javax.swing.JTextField();
        lb_Address = new javax.swing.JLabel();
        tb_Address = new javax.swing.JTextField();
        lb_Category = new javax.swing.JLabel();
        cmb_Category = new javax.swing.JComboBox<>();
        lb_Sub_Categoty = new javax.swing.JLabel();
        cmb_Sub_Category = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_View_Mobile = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_Back_Camera = new javax.swing.JLabel();
        lb_Colour = new javax.swing.JLabel();
        lb_Display = new javax.swing.JLabel();
        lb_Front_Camera = new javax.swing.JLabel();
        lb_Storage = new javax.swing.JLabel();
        lb_Warrenty = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_Price = new javax.swing.JLabel();
        lb_Prod_ID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_Quantity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_Details = new javax.swing.JTable();
        btn_Add_To_Craft = new javax.swing.JButton();
        lb_Bill = new javax.swing.JLabel();
        tb_Bill = new javax.swing.JTextField();
        lb_CGST = new javax.swing.JLabel();
        tb_CGST = new javax.swing.JTextField();
        lb_SGST = new javax.swing.JLabel();
        tb_SGST = new javax.swing.JTextField();
        btn_Total = new javax.swing.JButton();
        tb_Total = new javax.swing.JTextField();
        btn_Remove = new javax.swing.JButton();
        btn_Add1 = new javax.swing.JButton();
        lb_Sub_Categoty1 = new javax.swing.JLabel();
        tb_Quantity = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1501, 718));

        lb_Cust_ID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_Cust_ID.setText("Cust_ID:");

        tb_Cust_ID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lb_Name.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_Name.setText("Name");

        tb_Name.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lb_Mobi_No.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_Mobi_No.setText("Mobile Number");

        tb_Mob_No.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lb_Address.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_Address.setText("Address");

        tb_Address.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        lb_Category.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_Category.setText("Category :");

        cmb_Category.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmb_Category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_CategoryItemStateChanged(evt);
            }
        });
        cmb_Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_CategoryActionPerformed(evt);
            }
        });

        lb_Sub_Categoty.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_Sub_Categoty.setText("Sub-Category :");

        cmb_Sub_Category.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmb_Sub_Category.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_Sub_CategoryItemStateChanged(evt);
            }
        });
        cmb_Sub_Category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_Sub_CategoryMouseClicked(evt);
            }
        });

        table_View_Mobile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Back_Camera", "Front_Camera", "Colour", "Price", "Storage", "Warrenty", "Display", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_View_Mobile);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Back Camera");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Front Camera ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Colour  ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Storage");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Warrenty");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Display");

        lb_Back_Camera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Back_Camera.setText("1");

        lb_Colour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Colour.setText("3");

        lb_Display.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Display.setText("6");

        lb_Front_Camera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Front_Camera.setText("2");

        lb_Storage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Storage.setText("4");

        lb_Warrenty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Warrenty.setText("5");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("price");

        lb_Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Price.setText("7");

        lb_Prod_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Prod_ID.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Quantity");

        lb_Quantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_Quantity.setText(".....");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Product ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_Front_Camera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_Colour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_Back_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_Prod_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_Storage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_Warrenty, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(196, 196, 196))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lb_Prod_ID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Back_Camera)
                    .addComponent(jLabel5)
                    .addComponent(lb_Storage))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Front_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_Warrenty)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_Colour)
                    .addComponent(jLabel7)
                    .addComponent(lb_Display))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lb_Quantity)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_Price)
                            .addComponent(jLabel8))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Tb_Details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Back_Camera", "Front_Camera", "Colour", "Storage", "Warrenty", "Display", "Seling_Price"
            }
        ));
        Tb_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_DetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_Details);

        btn_Add_To_Craft.setText("ADD TO Craft");
        btn_Add_To_Craft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add_To_CraftActionPerformed(evt);
            }
        });

        lb_Bill.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_Bill.setText("Bill");

        tb_Bill.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_CGST.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_CGST.setText("CGST");

        tb_CGST.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        lb_SGST.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lb_SGST.setText("SGST");

        tb_SGST.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        btn_Total.setText("Total");
        btn_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TotalActionPerformed(evt);
            }
        });

        tb_Total.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        btn_Remove.setText("Remove");
        btn_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoveActionPerformed(evt);
            }
        });

        btn_Add1.setText("ADD ");
        btn_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add1ActionPerformed(evt);
            }
        });

        lb_Sub_Categoty1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_Sub_Categoty1.setText("Quantity");

        tb_Quantity.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_Sub_Categoty, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_Mobi_No, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lb_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lb_Cust_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_Sub_Categoty1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tb_Cust_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tb_Mob_No, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmb_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tb_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Add_To_Craft, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lb_CGST, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_CGST, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_SGST, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tb_SGST, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tb_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Cust_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tb_Cust_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Mobi_No, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tb_Mob_No, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lb_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(tb_Address)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Sub_Categoty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_Sub_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_Sub_Categoty1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tb_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btn_Add_To_Craft, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tb_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_CGST, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tb_CGST, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_SGST, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tb_SGST, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tb_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      java.sql.Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
     java.sql.Connection con1;
    private void cmb_CategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_CategoryItemStateChanged

       
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            String sql = "Select Sub_Category From tb_Sub_Category Where Category = '"+cmb_Category.getSelectedItem()+"' ";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            cmb_Sub_Category.removeAllItems();
            while(rs.next()){
                cmb_Sub_Category.addItem(rs.getString("Sub_Category"));
            }

            pst.close();
            rs.close();
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }

       

    }//GEN-LAST:event_cmb_CategoryItemStateChanged

     public void Updt_Cmb_Category(){
        
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
           
              String sql = "Select *from tb_Category";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            while(rs.next()){
                cmb_Category.addItem(rs.getString("Category"));
            }
           
            pst.close();
            rs.close();
            con.close();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
       
        
    }
    private void cmb_CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_CategoryActionPerformed

    
    private void cmb_Sub_CategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_Sub_CategoryItemStateChanged
       Table_View();
    }//GEN-LAST:event_cmb_Sub_CategoryItemStateChanged

     PreparedStatement insert;
    private void Table_View(){
         int c;
         
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            insert = con1.prepareStatement("select * From tb_Product_Details where Category = '"+cmb_Category.getSelectedItem()+"' And Sub_Category = '"+cmb_Sub_Category.getSelectedItem()+"'  ");
            
            ResultSet rs = insert.executeQuery();
             ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
             c = rsmd.getColumnCount();
             DefaultTableModel Dtm = (DefaultTableModel) Tb_Details.getModel();
            
           Dtm.setRowCount(0);
           
           while(rs.next()){
               Vector v2 = new Vector();
               for(int i = 1 ; i <= c; i++)
               {
                    v2.add(rs.getString("Prod_ID"));
                    v2.add(rs.getString("Back_Camera"));
                    v2.add(rs.getString("Front_Camera"));
                    v2.add(rs.getString("Colour"));
                    v2.add(rs.getString("Storage"));
                    v2.add(rs.getString("Warrenty"));
                    v2.add(rs.getString("Display"));
                     v2.add(rs.getString("Saling_Price"));
               }
               Dtm.addRow(v2);
           }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    private void cmb_Sub_CategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_Sub_CategoryMouseClicked

    }//GEN-LAST:event_cmb_Sub_CategoryMouseClicked

    private void Tb_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_DetailsMouseClicked
         int i = Tb_Details.getSelectedRow();
        TableModel model = Tb_Details.getModel();
        lb_Prod_ID.setText(model.getValueAt(i, 0).toString());
        lb_Back_Camera.setText(model.getValueAt(i, 1).toString());
        lb_Front_Camera.setText(model.getValueAt(i, 2).toString());
        lb_Colour.setText(model.getValueAt(i, 3).toString());
        lb_Storage.setText(model.getValueAt(i, 4).toString());
        lb_Warrenty.setText(model.getValueAt(i, 5).toString());
        lb_Display.setText(model.getValueAt(i, 6).toString());
        lb_Price.setText(model.getValueAt(i,7 ).toString());
        
         // To Get Quantity 
         Get_Quantity(); 
         
         
            
    }//GEN-LAST:event_Tb_DetailsMouseClicked

    private void btn_Add_To_CraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add_To_CraftActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            pst = con.prepareStatement("INSERT INTO add_customer(Cust_ID,Name,Mob_No,Address,Category,Sub_Category,Prod_ID,Back_Camera,Front_Camera,Colour,Storage,Warrenty,Display,Price,Quantity) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, tb_Cust_ID.getText());
            pst.setString(2, tb_Name.getText());
            pst.setString(3, tb_Mob_No.getText());
            pst.setString(4, tb_Address.getText());
            pst.setString(5, cmb_Category.getSelectedItem().toString());
            pst.setString(6, cmb_Sub_Category.getSelectedItem().toString());
            pst.setString(7, lb_Prod_ID.getText());
            pst.setString(8, lb_Back_Camera.getText());
            pst.setString(9, lb_Front_Camera.getText());
            pst.setString(10, lb_Colour.getText());
            pst.setString(11, lb_Storage.getText());
            pst.setString(12, lb_Warrenty.getText());
            pst.setString(13, lb_Display.getText());
            pst.setString(14, lb_Price.getText());
            pst.setString(15, tb_Quantity.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Product Added SuccessFully..");

            /// Update Stock

            int Quantity  =  Integer.parseInt(tb_Quantity.getText());
            int qty = Integer.parseInt(lb_Quantity.getText());
            int Total = qty - Quantity;

            pst = con.prepareStatement("Update  tb_Product_Details set Quantity = ? where Prod_ID = '"+lb_Prod_ID.getText()+"' ");
            pst.setString(1,String.valueOf(Total));

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, " Stock Updated SuccessFully.." +"\n" + " Now Stock Count Is " + Total);

            Get_Quantity();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        // ....code for copy record to jTable.
        int j = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            insert = con1.prepareStatement("select * From add_Customer where Cust_ID = "+tb_Cust_ID.getText()+" ");

            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
            j = rsmd.getColumnCount();
            DefaultTableModel Dtm = (DefaultTableModel) table_View_Mobile.getModel();

            Dtm.setRowCount(0);

            while(rs.next()){
                Vector v2 = new Vector();
                for(int i = 1 ; i <= j; i++)
                {
                    v2.add(rs.getString("Prod_ID"));
                    v2.add(rs.getString("Back_Camera"));
                    v2.add(rs.getString("Front_Camera"));
                    v2.add(rs.getString("Colour"));
                    v2.add(rs.getString("Price"));
                    v2.add(rs.getString("Storage"));
                    v2.add(rs.getString("Warrenty"));
                    v2.add(rs.getString("Display"));
                    v2.add(rs.getString("Quantity"));
                   
                }
                Dtm.addRow(v2);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        // ...code for add sum of Price.
       /*try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            String sql = "Select sum(Price) From add_Customer Where Cust_ID = "+tb_Cust_ID.getText()+" ";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();

            if(rs.next()){*/
                
                int price = Integer.parseInt(lb_Price.getText());
                int qnty = Integer.parseInt(tb_Quantity.getText());
                int val = price * qnty;
                
                JOptionPane.showMessageDialog(this, val);
                
                if(tb_Bill.getText() == "0"){
                    
                   
                    tb_Bill.setText(String.valueOf(val));
                    
                }
                else    
                {
                    int bill = Integer.parseInt(tb_Bill.getText());
                    int Ret = val + bill;
                    tb_Bill.setText(String.valueOf(Ret));
                    
                }
                
                //int sum = Integer.parseInt(rs.getString("sum(Price)"));
               // tb_Bill.setText(String.valueOf(sum));

          /*  }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
*/
    }//GEN-LAST:event_btn_Add_To_CraftActionPerformed

    private void btn_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TotalActionPerformed
        double bill = Double.parseDouble(tb_Bill.getText());
        int a = Integer.parseInt(tb_CGST.getText());
        double CGST = bill * a / 100;
        double SGST = CGST;

        double Tax = CGST + SGST;
        double Total = bill + Tax;

        String Val = String.format("%.2f", Total);
        tb_Total.setText((String)Val);
    }//GEN-LAST:event_btn_TotalActionPerformed

    private void btn_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoveActionPerformed
       
       
    }//GEN-LAST:event_btn_RemoveActionPerformed

    private void btn_Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add1ActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");

            pst = con.prepareStatement("INSERT INTO add_customer_info(Cust_ID,Bill,SGST,CGST,Total) VALUES(?,?,?,?,?)");
            pst.setString(1, tb_Cust_ID.getText());
            pst.setString(2, tb_Bill.getText());
            pst.setString(3, tb_SGST.getText());
            pst.setString(4, tb_CGST.getText());
            pst.setString(5, tb_Total.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "SuccessFull");

            tb_Name.setText("");
            lb_Quantity.setText("");
            tb_Mob_No.setText("");
            tb_Address.setText("");
            tb_Bill.setText("");
            tb_CGST.setText("");
            tb_SGST.setText("");
            tb_Total.setText("");
            lb_Prod_ID.setText("");
            lb_Storage.setText("");
            lb_Warrenty.setText("");
            lb_Price.setText("");
            lb_Display.setText("");
            lb_Colour.setText("");
            lb_Back_Camera.setText("");
            lb_Front_Camera.setText("");
            cmb_Category.setSelectedIndex(-1);
            cmb_Sub_Category.setSelectedIndex(-1);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_Add1ActionPerformed

    public void Get_Quantity(){
         
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
              con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Mobile_Shop_DB","root","");
            
            String sql = "Select * From tb_product_details where Prod_ID = '"+lb_Prod_ID.getText()+"' " ;
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            rs = pst.executeQuery();
            
            if(rs.next()){
                lb_Quantity.setText(rs.getString("Quantity"));
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Add_New_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
          
       
    }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tb_Details;
    private javax.swing.JButton btn_Add1;
    private javax.swing.JButton btn_Add_To_Craft;
    private javax.swing.JButton btn_Remove;
    private javax.swing.JButton btn_Total;
    private javax.swing.JComboBox<String> cmb_Category;
    private javax.swing.JComboBox<String> cmb_Sub_Category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_Address;
    private javax.swing.JLabel lb_Back_Camera;
    private javax.swing.JLabel lb_Bill;
    private javax.swing.JLabel lb_CGST;
    private javax.swing.JLabel lb_Category;
    private javax.swing.JLabel lb_Colour;
    private javax.swing.JLabel lb_Cust_ID;
    private javax.swing.JLabel lb_Display;
    private javax.swing.JLabel lb_Front_Camera;
    private javax.swing.JLabel lb_Mobi_No;
    private javax.swing.JLabel lb_Name;
    private javax.swing.JLabel lb_Price;
    private javax.swing.JLabel lb_Prod_ID;
    private javax.swing.JLabel lb_Quantity;
    private javax.swing.JLabel lb_SGST;
    private javax.swing.JLabel lb_Storage;
    private javax.swing.JLabel lb_Sub_Categoty;
    private javax.swing.JLabel lb_Sub_Categoty1;
    private javax.swing.JLabel lb_Warrenty;
    private javax.swing.JTable table_View_Mobile;
    private javax.swing.JTextField tb_Address;
    private javax.swing.JTextField tb_Bill;
    private javax.swing.JTextField tb_CGST;
    private javax.swing.JTextField tb_Cust_ID;
    private javax.swing.JTextField tb_Mob_No;
    private javax.swing.JTextField tb_Name;
    private javax.swing.JTextField tb_Quantity;
    private javax.swing.JTextField tb_SGST;
    private javax.swing.JTextField tb_Total;
    // End of variables declaration//GEN-END:variables
}
