/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;

/**
 *
 * @author sai
 */
public class frm_Stock extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_Stock
     */
    public frm_Stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_Header = new javax.swing.JPanel();
        btn_Stock = new javax.swing.JButton();
        btn_View_Stock = new javax.swing.JButton();
        pnl_Body = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        btn_Stock.setText("Add Stock");
        btn_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StockActionPerformed(evt);
            }
        });

        btn_View_Stock.setText("View Stock");
        btn_View_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_View_StockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_HeaderLayout = new javax.swing.GroupLayout(Pnl_Header);
        Pnl_Header.setLayout(Pnl_HeaderLayout);
        Pnl_HeaderLayout.setHorizontalGroup(
            Pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_View_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(970, Short.MAX_VALUE))
        );
        Pnl_HeaderLayout.setVerticalGroup(
            Pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_HeaderLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(Pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_View_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_BodyLayout = new javax.swing.GroupLayout(pnl_Body);
        pnl_Body.setLayout(pnl_BodyLayout);
        pnl_BodyLayout.setHorizontalGroup(
            pnl_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1275, Short.MAX_VALUE)
        );
        pnl_BodyLayout.setVerticalGroup(
            pnl_BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(pnl_Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Pnl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 682, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(76, Short.MAX_VALUE)
                    .addComponent(pnl_Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StockActionPerformed
        
         pnl_Body.removeAll();
        pnl_Body.repaint();
        
        frm_Add_Stock obj = new frm_Add_Stock();
        pnl_Body.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_StockActionPerformed

    private void btn_View_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_View_StockActionPerformed
        
         pnl_Body.removeAll();
        pnl_Body.repaint();
        
        frm_View_Stocks obj = new frm_View_Stocks();
        pnl_Body.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_View_StockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pnl_Header;
    private javax.swing.JButton btn_Stock;
    private javax.swing.JButton btn_View_Stock;
    private javax.swing.JPanel pnl_Body;
    // End of variables declaration//GEN-END:variables
}
