/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;

import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author sai
 */
public class mdi extends javax.swing.JFrame {

  
    public mdi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sider_Panel = new javax.swing.JPanel();
        btn_Product = new javax.swing.JButton();
        btn_Stock = new javax.swing.JButton();
        btn_Category = new javax.swing.JButton();
        btn_Distrubutor = new javax.swing.JButton();
        btn_Customer4 = new javax.swing.JButton();
        main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sider_Panel.setBackground(new java.awt.Color(102, 102, 255));

        btn_Product.setText("Product");
        btn_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductActionPerformed(evt);
            }
        });

        btn_Stock.setText("Stock");
        btn_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StockActionPerformed(evt);
            }
        });

        btn_Category.setText("Category");
        btn_Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CategoryActionPerformed(evt);
            }
        });

        btn_Distrubutor.setText("Distrubutor");
        btn_Distrubutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DistrubutorActionPerformed(evt);
            }
        });

        btn_Customer4.setText("Customer");
        btn_Customer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Customer4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sider_PanelLayout = new javax.swing.GroupLayout(sider_Panel);
        sider_Panel.setLayout(sider_PanelLayout);
        sider_PanelLayout.setHorizontalGroup(
            sider_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sider_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sider_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(btn_Product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Category, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(btn_Distrubutor, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(btn_Customer4, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                .addContainerGap())
        );
        sider_PanelLayout.setVerticalGroup(
            sider_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sider_PanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btn_Customer4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Category, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Distrubutor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(644, Short.MAX_VALUE))
        );

        main.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1653, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sider_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sider_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductActionPerformed
       
      main.removeAll();
      main.repaint();
      
        frm_Product obj = new frm_Product();
        main.add(obj);
        obj.setVisible(true);
       
       
        
    }//GEN-LAST:event_btn_ProductActionPerformed

    private void btn_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StockActionPerformed
         main.removeAll();
        main.repaint();
        
        frm_Stock obj = new frm_Stock();
        main.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_StockActionPerformed

    private void btn_CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CategoryActionPerformed
         main.removeAll();
        main.repaint();
        
        frm_Category obj = new frm_Category();
        main.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_CategoryActionPerformed

    private void btn_DistrubutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DistrubutorActionPerformed
          main.removeAll();
        main.repaint();
        
        frm_Distrubutor obj = new frm_Distrubutor();
        main.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_DistrubutorActionPerformed

    private void btn_Customer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Customer4ActionPerformed
          main.removeAll();
        main.repaint();
        
        frm_Customer obj = new frm_Customer();
        main.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_Customer4ActionPerformed
    
    public void CenterJIF(JInternalFrame jif){
        
        
        main.add(jif);
         Dimension desktopSize = main.getSize();
         Dimension JInternalFrame = jif.getSize();
         
         int width = ( desktopSize.width - JInternalFrame.width ) / 2;
         int height = ( desktopSize.height - JInternalFrame.height ) / 2;
         
         jif.setLocation(width, height);
         jif.setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Category;
    private javax.swing.JButton btn_Customer4;
    private javax.swing.JButton btn_Distrubutor;
    private javax.swing.JButton btn_Product;
    private javax.swing.JButton btn_Stock;
    private javax.swing.JPanel main;
    private javax.swing.JPanel sider_Panel;
    // End of variables declaration//GEN-END:variables
}
