/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg_Mobile_Shop;

/**
 *
 * @author sai
 */
public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Sm_Available_Stock = new javax.swing.JMenuBar();
        Mn_Customer = new javax.swing.JMenu();
        Sm_Add_New_Customer = new javax.swing.JMenu();
        Mn_Product = new javax.swing.JMenu();
        Sm_Add_New_Product = new javax.swing.JMenu();
        Mn_Category = new javax.swing.JMenu();
        Sm_Add_Category = new javax.swing.JMenu();
        Sm_Add_Sub_Category = new javax.swing.JMenu();
        Mn_Stock = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 972, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        Mn_Customer.setText("Customer");

        Sm_Add_New_Customer.setText("Add New Customer");
        Mn_Customer.add(Sm_Add_New_Customer);

        Sm_Available_Stock.add(Mn_Customer);

        Mn_Product.setText("Product");

        Sm_Add_New_Product.setText("Add New Product");
        Mn_Product.add(Sm_Add_New_Product);

        Sm_Available_Stock.add(Mn_Product);

        Mn_Category.setText("Category");

        Sm_Add_Category.setText("Add Category");
        Mn_Category.add(Sm_Add_Category);

        Sm_Add_Sub_Category.setText("Add Sub Category");
        Mn_Category.add(Sm_Add_Sub_Category);

        Sm_Available_Stock.add(Mn_Category);

        Mn_Stock.setText("Stock");

        jMenu1.setText("Available Stock");
        Mn_Stock.add(jMenu1);

        Sm_Available_Stock.add(Mn_Stock);

        setJMenuBar(Sm_Available_Stock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mn_Category;
    private javax.swing.JMenu Mn_Customer;
    private javax.swing.JMenu Mn_Product;
    private javax.swing.JMenu Mn_Stock;
    private javax.swing.JMenu Sm_Add_Category;
    private javax.swing.JMenu Sm_Add_New_Customer;
    private javax.swing.JMenu Sm_Add_New_Product;
    private javax.swing.JMenu Sm_Add_Sub_Category;
    private javax.swing.JMenuBar Sm_Available_Stock;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
